In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import recommendations
from sklearn.cluster import KMeans
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [15]:
df = pd.read_csv('../datasets/processed_course_clustering_dataset.csv')
df = df[['Student Number', 'Course Code', 'Letter Grade', 'Semester', 'Course Credit', 'Course Year'] + list(df.columns[20:])]
df

,Student Number,Course Code,Letter Grade,Semester,Course Credit,Course Year,Subject,A+ rate,A rate,A- rate,...,C rate,C- rate,D+ rate,D rate,D- rate,F rate,Mean GPA - Students taken,Mean Grade - Students taken,STDEV GPA - Students taken,STDEV Grade - Students taken
0,1182,MGT 511,A-,2011 - Fall,3,5,MGT,0.000000,0.396226,0.226415,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.018868,3.363396,3.479245,0.583240,0.712352
1,134,UNI 123,C-,2011 - Fall,3,1,UNI,0.019355,0.096774,0.064516,...,0.045161,0.051613,0.038710,0.058065,0.032258,0.187097,2.410000,2.178710,1.082217,1.378734
2,217,UNI 115,A-,2011 - Fall,3,1,UNI,0.097561,0.243902,0.219512,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.048780,2.892927,3.360976,1.048528,0.917845
3,1227,MGT 511,B,2011 - Fall,3,5,MGT,0.000000,0.396226,0.226415,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.018868,3.363396,3.479245,0.583240,0.712352
4,1225,MGT 541,B+,2011 - Fall,3,5,MGT,0.000000,0.285714,0.285714,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.095238,3.285238,3.238095,0.526513,1.155195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49342,1311,EECS 216,F,2014 - Spring,3,2,EECS,0.000000,0.011173,0.033520,...,0.061453,0.072626,0.067039,0.117318,0.106145,0.413408,2.293039,1.005525,0.689455,1.125647
49343,1311,EECS 202,D+,2014 - Spring,3,2,EECS,0.045198,0.028249,0.062147,...,0.101695,0.101695,0.039548,0.101695,0.050847,0.141243,2.334802,1.980226,0.767389,1.233161
49344,1311,EECS 218,B-,2014 - Spring,3,2,EECS,0.028302,0.066038,0.037736,...,0.103774,0.084906,0.132075,0.037736,0.000000,0.094340,2.378774,2.274528,0.779391,1.134151
49345,173,CTV 212,C+,2014 - Spring,3,2,CTV,0.000000,0.088235,0.191176,...,0.073529,0.058824,0.014706,0.044118,0.000000,0.088235,2.556806,2.693056,0.864821,1.162238
49346,789,ISS 214,A-,2014 - Spring,3,2,ISS,0.200000,0.114286,0.200000,...,0.000000,0.000000,0.028571,0.000000,0.000000,0.028571,2.978000,3.285714,0.630568,0.896773

In [12]:
df = pd.concat([df, pd.get_dummies(df['Subject'], prefix='Subject'), pd.get_dummies(df['Course Year'], prefix='Course Year')], axis=1)
df.drop(['Subject', 'Course Year'], axis=1, inplace=True)

In [4]:
numerical_grades = {'A+': 4.1, 'A': 4.0, 'A-': 3.7, 'B+': 3.3, 'B': 3.0, 'B-': 2.7, 'C+': 2.3, 'C': 2.0,
                    'C-': 1.7, 'D+': 1.3, 'D': 1.0, 'D-': 0.5, 'F': 0.0}

In [5]:
course_credits = {}
for row_idx in df.index:
    course_code = df.iloc[row_idx, 1]
    credit = df.iloc[row_idx, 4]    
    course_credits[course_code] = credit

In [6]:
def get_semester_data(semester_name):
    semester_data = {}   # semester data in shape {student_number: {course_code: letter_grade, ...}, ...}
    
    # extracting the instances with the given semester_name from the main dataFrame
    dataset = df[df.iloc[:, 3] == semester_name]
    dataset.index = range(len(dataset))
    
    # filling the semester_data dictionary
    for row_idx in dataset.index:
        student_number = dataset.iloc[row_idx, 0]
        course_code = dataset.iloc[row_idx, 1]
        letter_grade = dataset.iloc[row_idx, 2]
        
        semester_data.setdefault(student_number, {})
        semester_data[student_number][course_code] = numerical_grades[letter_grade]
    
    return semester_data

In [7]:
def get_avg_gpa(train_semester, student):
    courses = train_semester[student]
    total_credit = 0
    weights = 0
    for course in courses:
        total_credit += course_credits[course]
        weights += courses[course] * course_credits[course]
    
    return weights / total_credit

In [8]:
def fit_cluster(train_sems, num_clusters, training_data, cluster_model):
    train_dataset = pd.DataFrame(columns=df.columns)
    
    # extracting instances from the dataset which should be in training data
    for sem in train_sems:
        train_dataset = pd.concat([train_dataset, df[df.iloc[:, 3] == sem]], ignore_index=True)

    cluster_features = train_dataset[list(train_dataset.columns[4:])]
    
    # fitting a clustering model based on GPA, Completed Credits and Departments
    fitted_cluster_model = cluster_model(n_clusters=num_clusters).fit(cluster_features)
    cluster_labels = fitted_cluster_model.labels_
    
    cluster_dataset = {}   # splitting the train dataset into sub-dicts based on their predicted cluster label
    
    # assigning each students' data to their predicted clusters
    for i in range(len(cluster_labels)):
        cluster_dataset.setdefault(cluster_labels[i], {})
        student_number = train_dataset.iloc[i, 0]
        cluster_dataset[cluster_labels[i]][student_number] = training_data[student_number]
    
    return cluster_dataset, fitted_cluster_model

In [9]:
def cluster_test_data(cluster_model, semester_name):
    # extracting all instances with the given semester_name from the main dataFrame
    test_dataset = df[df.iloc[:, 3] == semester_name]
    test_dataset.index = range(len(test_dataset))
    
    # predicting the cluster labels of test data using a cluster model fitted on the train data so far
    cluster_features = test_dataset[list(test_dataset.columns[4:])]
    cluster_labels = cluster_model.predict(cluster_features)
    
    # getting the semester data of available students in test semester
    semester_data = get_semester_data(semester_name)
    
    cluster_dataset = {}   # splitting the test dataset into sub-dicts based on their predicted cluster label
    
    # assigning each students' data to their predicted clusters
    for i in range(len(cluster_labels)):
        cluster_dataset.setdefault(cluster_labels[i], {})
        student_number = test_dataset.iloc[i, 0]
        cluster_dataset[cluster_labels[i]][student_number] = semester_data[student_number]
    return cluster_dataset

In [ ]:
def get_errors(train_semester, test_semester, sim):
    average_gpa = {}
    y_true = []
    y_pred = []
    
    # predicting recommended courses for each student in training data
    for student in train_semester:
        recommended_courses = {}
        recs = recommendations.getRecommendations(train_semester, student, sim)
        
        for rec_grade, rec_course in recs:
            recommended_courses.setdefault(rec_course, rec_grade)
            
        average_gpa.setdefault(student, get_avg_gpa(train_semester, student))
        
        # skipping students from training data who do not have not taken courses in test data
        if student not in test_semester:
            continue
            
        # checking for students' test data records in recommended courses
        for course_code in test_semester[student]:
            y_true.append(test_semester[student][course_code])
            if course_code in recommended_courses:   # considering the predicted grade if course is availabel
                y_pred.append(recommended_courses[course_code])
            else:   # considering the average GPA if course is not available in recommended courses
                y_pred.append(average_gpa[student])
        
    # calculating the error metrics
    if len(y_true) == 0:
        rmse = None
        mae = None
    else:
        rmse = np.sqrt(mean_squared_error(y_true, y_pred))
        mae = mean_absolute_error(y_true, y_pred)
    
    return rmse, mae

In [ ]:
def predict(sim, cluster_model):
    error_scores = {} # storing error scores in a dict with shape: 
                      # {num_clusters (k=2,3,...,7): 
                        # {num_training_semesters (N=1,2,...,7): 
                            # {cluster_label: [RMSE, MAE], ...}, 
                        # ...}, 
                      #...}
    
    sorted_semesters = sorted(set(df.iloc[:, 3]))   # sorting semesters in a time series manner
    for num_clusters in range(2, 8):
        error_scores.setdefault(str(num_clusters), {})
        train_semester = {}   # {student_number: {course_code: letter_grade, ...}, ...}
        for sem_idx in range(1, len(sorted_semesters)):
            error_scores[str(num_clusters)].setdefault(str(sem_idx), {})
            
            # combining all previous semesters in dataset and consider it as training semester
            new_semester = get_semester_data(sorted_semesters[sem_idx-1])
            for student in new_semester:
                if student in train_semester:   # combine data if a student already exist
                    train_semester[student].update(new_semester[student])
                else:   # create a new key-value pair for students with no record
                    train_semester[student] = new_semester[student]
            
            training_semesters_name = sorted_semesters[:sem_idx]   # names of all training semesters
            
            # getting the cluster model fitted on training data and each clusters' training data
            train_cluster_data, fitted_cluster_model = fit_cluster(training_semesters_name, num_clusters, train_semester, cluster_model)
            
            # getting the clustered test data
            test_semester_name = sorted_semesters[sem_idx]
            test_cluster_data = cluster_test_data(fitted_cluster_model, test_semester_name)
            
            # fitting each cluster label with a similarity metric, and measure the error between the same
            # cluster labels in training and test data
            for cluster_label in train_cluster_data:
                rmse, mae = get_errors(train_cluster_data[cluster_label], test_cluster_data[cluster_label], sim)
                error_scores[str(num_clusters)][str(sem_idx)][str(cluster_label)] = [rmse, mae]
        
    return error_scores

In [ ]:
model_errors = {}

In [ ]:
errors = predict(recommendations.sim_distance, KMeans)
model_errors['Euclidean Distance'] = errors

In [ ]:
errors = predict(recommendations.sim_jaccard, KMeans)
model_errors['Jaccard Index'] = errors

In [ ]:
errors = predict(recommendations.sim_pearson, KMeans)
model_errors['Pearson Correlation'] = errors

In [ ]:
with open('clustering_based_collaborative_filtering_results (Course based with KMeans).json', 'w') as fw:
    json.dump(model_errors, fw)